# Use Node.js as the base image
FROM node:20

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install --legacy-peer-deps

# Copy entire client folder
COPY . .

# Build React app
RUN npm run build

# Expose the client port
EXPOSE 3000
CMD ["npm", "start"]