services:
  server:
    image: smsraj2001/shoe-shop:server-latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - BRAINTREE_MERCHANT_ID=${BRAINTREE_MERCHANT_ID}
      - BRAINTREE_PUBLIC_KEY=${BRAINTREE_PUBLIC_KEY}
      - BRAINTREE_PRIVATE_KEY=${BRAINTREE_PRIVATE_KEY}

  client:
    image: smsraj2001/shoe-shop:client-latest
    ports:
      - "3000:3000"
    depends_on:
      - server